log_format detailed '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent" '
                    'headers_in:$http_host|$http_user_agent|$http_accept|$http_accept_encoding|$http_accept_language|$http_origin|$http_authorization';

upstream gateway_upstream {
    server gateway:8080;
}

server {
    listen       80;
    server_name  localhost;
    client_max_body_size 20m;

    access_log /dev/stdout detailed;
    error_log /dev/stderr info;

    location / {
        root   /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://gateway_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_connect_timeout 10m;
        proxy_read_timeout 10m;
        proxy_send_timeout 10m;
    }

    location /oauth2/ {
        proxy_pass http://gateway_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_connect_timeout 10m;
        proxy_read_timeout 10m;
        proxy_send_timeout 10m;
    }

    location /login/ {
        proxy_pass http://gateway_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_connect_timeout 10m;
        proxy_read_timeout 10m;
        proxy_send_timeout 10m;
    }

    location /logout {
        proxy_pass http://gateway_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_connect_timeout 10m;
        proxy_read_timeout 10m;
        proxy_send_timeout 10m;
    }
}
