spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
      httpclient:
        connect-timeout: 10000       # en ms
        response-timeout: 600s      # durée max d’attente de la réponse      
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://dummy
  codec:
    max-in-memory-size: 10MB

services:
  rag:
    uri: http://rag-service:8080
  document:
    uri: http://document-service:8080
  user:
    uri: http://user-service:8080

security:
  jwt:
    secret: ${JWT_SECRET:0123456789abcdef0123456789abcdef}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
